FROM ubuntu:14.04
MAINTAINER rick.doucet@implementingeventsourcingwithfsharp.com

#Update the apr-get repos
RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get -y install wget

# add the .net core package to the apt-get repos
RUN sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
RUN apt-get update

# add the jenkins package to the apt-get repos
RUN wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
RUN sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN apt-get update

#install Java => Copied from https://www.ivankrizsan.se/2015/08/08/creating-a-docker-image-with-ubuntu-and-java/
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

#install jenkins
RUN apt-get -y install jenkins
RUN apt-get -y install curl

# intall .net code
RUN apt-get -y install dotnet=1.0.0.001598-1


#expose the port
EXPOSE 8080

#Configure jenkins through CLI

RUN echo "/etc/init.d/jenkins start" > jenkins-wait.sh
RUN echo "until \$(curl --output /dev/null --silent --head --fail http://127.0.0.1:8080); do" >> jenkins-wait.sh
RUN echo "  printf '.'" >> jenkins-wait.sh
RUN echo "  sleep  .5" >> jenkins-wait.sh
RUN echo "done;" >> jenkins-wait.sh


RUN chmod 777 jenkins-wait.sh
RUN ./jenkins-wait.sh

#Hack waiting for jenkins to be completely up
RUN sleep 5m
RUN java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin github -restart

#start jenkins when the container starts
CMD /etc/init.d/jenkins start ; bash



#cleanup
RUN apt-get -y remove wget
RUN apt-get -y remove curl