FROM jenkins
MAINTAINER rick.doucet@implementingeventsourcingwithfsharp.com

# add the .net code package to the apt-get repos
RUN sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
RUN apt-get update

# intall .net code
RUN apt-get install dotnet=1.0.0.001598-1