FROM ubuntu:14.04
MAINTAINER rick.doucet@implementingeventsourcingwithfsharp.com

#Update the apr-get repos
RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get install -y wget

# install server dependencies
RUN apt-get update
RUN apt-get install -y openjdk-7-jre-headless

# install build agent dependencies
RUN apt-get install -y git

# install team city
RUN wget -c https://download.jetbrains.com/teamcity/TeamCity-9.0.3.tar.gz -O /tmp/TeamCity-9.0.3.tar.gz
RUN tar -xvf /tmp/TeamCity-9.0.3.tar.gz -C /srv
RUN rm -rf /tmp/TeamCity-9.0.3.tar.gz
RUN mkdir /srv/.BuildServer

# create user
RUN useradd -m teamcity
RUN chown -R teamcity /srv/TeamCity
RUN chown -R teamcity /srv/.BuildServer

# create init.d script
RUN wget https://gist.githubusercontent.com/sandcastle/9282638/raw/teamcity-init.sh -O /etc/init.d/teamcity
RUN chmod 775 /etc/init.d/teamcity
RUN update-rc.d teamcity defaults

# download postgres
RUN mkdir -p /srv/.BuildServer/lib/jdbc
RUN mkdir -p /srv/.BuildServer/config
RUN wget http://jdbc.postgresql.org/download/postgresql-9.3-1101.jdbc41.jar -O /srv/.BuildServer/lib/jdbc/postgresql-9.3-1101.jdbc41.jar
RUN wget https://gist.githubusercontent.com/sandcastle/9282638/raw/postgres.database.properties -O /srv/.BuildServer/config/database.properties


RUN nano /etc/nginx/sites-available/teamcity
RUN rm -rf /etc/nginx/sites-enabled/default
RUN rm -rf /etc/nginx/sites-available/default

RUN /etc/init.d/nginx start
RUN /etc/init.d/teamcity start

RUN apt-get remove -y wget
